### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by xNicklaj**
Okay, I've been able to create the pull request. I don't know if I've got everthing right on the programming side, but I should.
Anyway I need to discuss about an issue that occurs with my alexa whenever you can.

To be honest I don't know why Index keeps appearing as .json since in my computer it's a .js
Anyway it's to not that it's a .js, just like the original index from the master branch

### CODE REVIEW

**Comment by reger-men** [comment]
You have to make some changes:
e.g. the function `GetVideoIntent` is used for the english language and `GetVideoGermanIntent` for the german version. Your new function should call something like that `GetVideoItalianIntent`. 


Every function you insert, should relate to the Italian version. So you can pick one languages without conflict.

Once you done, create the pull request only with the files that you have modified or inserted.

**Comment by xNicklaj** [comment]
sure I will. Could you tell me in which subfolder can I find the base GetVideoIntent function?

**Comment by reger-men** [comment]
You may find the function `GetVideoGermanIntent` into `index.js 631` and the call come from `Interaction-Model-German.json 47`. For the Italian version you should copy the `Interaction-Model-German.json`  and rename it to `Interaction-Model-Italian.json` than replace every `German` word with `Italian`.

The next step is to copy each function related to `Interaction-Model-German.json` in `index.js` and replace they with the new functions names from your `Interaction-Model-Italian.json`. That should be work.

**Review by reger-men — APPROVED** [review]

**Review by reger-men — CHANGES_REQUESTED** [review]
This file is only an copy of the `Interaction-Model.json ` where you made the changes?

**Comment by reger-men** [comment]
Here is an useful [link ](https://drupal.gatech.edu/handbook/using-pull-requests-forks) to fork and create pull request  When you run `git add filename.xx` make sure you add only files you changed or you want to pull. Use after `git add` `git commit -m "your message"` to explain what changes you did.

**Pull request closed without merging**
